### ISSUE TITLE
Why are you hosting the downloads on mega.nz?

### ISSUE THREAD

**Issue by Fortanono** [BBoldt/ThePioneers#1]
I believe that your download is clean, but I can't be sure that there isn't any malware on it added by the shady website. I really wanted to try this modpack, but I don't want to wreck the computer I got for Christmas.

**Comment by BBoldt** [comment]
Why do you think mega.nz is a shady website?

It's just a place for sharing large files like dropbox or onedrive.

**Comment by BBoldt** [comment]
Either way, this pack will be on a launcher soon.

The versions linked to on github are extremely early builds, and very buggy.

**Comment by Fortanono** [comment]
Sorry, I thought it was... The fact it has a download manager and slows down your download if you don't download it kinda made me jump to conclusions. I downloaded the pack, and nothing bad happened.

**Comment by BBoldt** [comment]
moved to github releases:

https://github.com/BBoldt/ThePioneers/releases

the 0.5 alpha on there is brand new btw, I just forgot to change the version number
