### ISSUE TITLE
Only dough from the Create mod can be cooked into bread; dough from Bakery or from Candlelight Dinner cannot be cooked

### ISSUE THREAD

**Issue by krumble1** [BBoldt/ThePioneers#104]
**Modpack Version:** 5.6.2

**Issue Description:**
Only the dough from _Create_ can be cooked into bread. _Bakery_ dough and _Candlelight Dinner_ dough cannot be smelted or cooked in any way. Is this intended, or are the three types of dough supposed to be interchangeable?

**Steps to Reproduce:**
Put doughs from _Create_, _Bakery_, and _Candlelight Dinner_ into furnace along with some fuel. Observe differences.

**Comment by BBoldt** [comment]
Bakery dough is meant to be used only in the bakery oven, not a furnace, as cooking it results in different types of breads.

Create dough is the only one really meant to be used in a furnace. Though it too is compatible with the Bakery oven. There is also a mine colonies dough which I will add to the dough tag so it will work in the other recipes also.

![](https://i.imgur.com/oSoZAm9.png)

I'm going to leave this one as is. Craft an oven or baking station to be able to use all types of dough.
