### ISSUE TITLE
Status effects overlap with inventory tabs

### ISSUE THREAD

**Issue by krumble1** [BBoldt/ThePioneers#105]
**Modpack Version:** 5.6.2

**Issue Description:**

<img width="576" alt="image" src="https://github.com/BBoldt/ThePioneers/assets/12228024/4fc067fb-cf24-41af-a162-8e24a3f072ab">

**Steps to Reproduce:**
Have status effects. View inventory.

**Comment by BBoldt** [comment]
Adding this mod should solve it, I'll get it in the next release.

If you want you can try it out yourself, it's clientside I believe.

https://www.curseforge.com/minecraft/mc-mods/stylish-effects
