### ISSUE TITLE
Wood items made with Architect's Cutter cannot be used as fuel

### ISSUE THREAD

**Issue by krumble1** [BBoldt/ThePioneers#106]
**Modpack Version:** 5.6.2

**Issue Description:**
Wood items made with Architect's Cutter from _Domum Ornamentum_ cannot be used in furnaces as fuel

**Steps to Reproduce:**
Create a wood item on the Architect's Cutter (I made a log half-slab) and try to place it in a furnace

**Comment by BBoldt** [comment]
Sorry this is not something I want to mess with.

I don't know how to properly add fuel values to the blocks created with the architect's cutter.

My recommendation is to try suggesting it to the minecolonies devs.

**Comment by BBoldt** [comment]
It has already been suggested here:

https://github.com/ldtteam/Domum-Ornamentum/issues/215
