### ISSUE TITLE
Suggestion: make EnderIO Alloy Smelter recipes and Thermal Series Induction Smelter recipes interchangeable

### ISSUE THREAD

**Issue by krumble1** [BBoldt/ThePioneers#107]
**Modpack Version:** 5.6.2

**Suggestion Description:**
Would it break any progression that you can think of to make _EnderIO_ Alloy Smelter (and Primitive Alloy Smelter) recipes and _Thermal Series_ Induction Smelter recipes interchangeable? (Except for the _Thermal Series_ recipes that require a catalyst, since the Alloy Smelter has no slot for a catalyst.)

For example, the brass ingot from _Create_ (made by smelting a _Create_ zinc ingot along with any copper ingot or dust) can be made in the _Thermal Series_ Induction Smelter or in a heated mixer from _Create_ but that recipe does not show an option to be made in the EnderIO Alloy Smelter (or Primitive Alloy Smelter).

**Comment by BBoldt** [comment]
I'll see what I can do about this, I'm all for more compatibility. Depending on how tedious it is it might just be a few extra recipes (such as brass).

**Comment by BBoldt** [comment]
This isn't actually that difficult to accomplish.

I am making alloys work in EIO, Thermal, and Create.

just one example:
![](https://i.imgur.com/0zKz1JQ.png)
![](https://i.imgur.com/bWM2pMf.png)
![](https://i.imgur.com/Gme8pQr.png)

**Comment by BBoldt** [comment]
Recipes supported on all 3 (EIO, Thermal, & Create) include most metals and a few special recipes from EIO and Thermal.
