### ISSUE TITLE
Crash when breaking a specific architectural roof tile

### ISSUE THREAD

**Issue by kaimokene** [BBoldt/ThePioneers#11]
When you use Botania's any colored Petal blocks in architectural table you get "white version of it".
When you place it down it will appear again white version of it, but when you break it it crashes
It seems like something to do with nbt and architecturecraft Crash report: http://pastebin.com/TvbL8wU6

**Comment by BBoldt** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2489461-architecturecraft-1-3-1-for-minecraft-1-8-8-1-8-9?comment=122
