### ISSUE TITLE
👽

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/ThePioneers#111]
????????

![](https://i.imgur.com/ihal1YB.png)

**Comment by jellimoonez** [comment]
literally my same issue... what the flip!!!!!!!!!!!!!!!!!
![alien](https://github.com/BBoldt/ThePioneers/assets/160393981/1eb8c940-5f71-4b20-9de3-291f15542f5e)

**Comment by StressedHelp** [comment]
![ALIOEN](https://github.com/BBoldt/ThePioneers/assets/125163442/db66dad3-90bc-4db9-9d4f-b8856c42d399)

**Comment by BBoldt** [comment]
https://www.curseforge.com/minecraft/mc-mods/r-e-a-l
