### ISSUE TITLE
Gloves such as diamond gloves can't be equipped in the "Hands" curio slot, only the "Curio" curio slot

### ISSUE THREAD

**Issue by krumble1** [BBoldt/ThePioneers#114]
**Modpack Version:**
5.7

**Issue Description:**
Gloves such as diamond gloves can't be equipped in the "Hands" curio slot, only the "Curio" curio slot. Not sure if this is intended or not.

**Steps to Reproduce:**
Try to place diamond glove into the curio slot labeled "Hands", then try to place diamond gloves into the curio slot labeled "Curio".

**Comment by BBoldt** [comment]
They are meant to go in the aether's curio slots, which are opened in a separate tab.
