### ISSUE TITLE
Gravel drops instead of cobblestone when mining - server only.

### ISSUE THREAD

**Issue by Apocryphai** [BBoldt/ThePioneers#13]
I've set The Pioneers up as a local server. I had to disable CustomMainMenu, defaultoptions, MouseTweaks, Neat and ResourceLoader to get it to run.

However when I log onto it and mine stone it drops gravel instead of cobblestone. This happens with vanilla tools as well as TiCon tools.

This doesn't happen when I create and play a singleplayer world.

**Comment by kaimokene** [comment]
I know what is the problem open the servers config folder and open vtweaks.cfg and disable the gravel config cant remember the name

**Comment by Apocryphai** [comment]
Yep, that fixed it, thank you! The vtweaks.cfg line was this one:
```
# This config allows for flint and gravel to be a reasonably heavy part of crafting / early-game gameplay
B:"Change Base Game Mechanics?"=true
```
Changing "true" to "false" sorted it.

**Comment by BBoldt** [comment]
Did you forget to copy over the config folder?

**Comment by Apocryphai** [comment]
Doh, yeah I did. My bad.

**Comment by BBoldt** [comment]
Don't forget you need the "scripts" folder as well, for minetweaker stuff.

**Comment by Apocryphai** [comment]
Somehow I remembered the scripts folder but not the config one! However, now that I've undone my derps, really nice pack, thanks :-)
