### ISSUE TITLE
Recipe Conflict - Storage Crate & 4x4 Storage Drawers

### ISSUE THREAD

**Issue by Knickerbockergl** [BBoldt/ThePioneers#14]
The Storage Crate from Actually Additions and the 4x4 Storage Drawer from Storage Drawers share the same recipe. Only the Storage Crate is craftable in game.

**Comment by BBoldt** [comment]
It's fine on my end, have you somehow missed getting the "scripts" folder?

![](http://i.imgur.com/kNejOj3.png)
