### ISSUE TITLE
Hide BuildingBricks items using the config

### ISSUE THREAD

**Issue by hea3ven** [BBoldt/ThePioneers#17]
There's a config option to disable the trowels on the creative menu/JEI: https://github.com/BBoldt/ThePioneers/blob/master/config/BuildingBricks/general.cfg#L11. Also, I've just made an issue to remember to add a config for the blocks too (https://github.com/hea3ven/BuildingBricks/issues/34). This will make it so you don't have to constantly add to the JEI blacklist when new materials get added.

**Comment by BBoldt** [comment]
Cool, thanks!
