### ISSUE TITLE
Bug: Chisel and Tinker's construct

### ISSUE THREAD

**Issue by Doppelganker** [BBoldt/ThePioneers#19]
When trying to mine chisel blocks with stone pick from tinkers, the block is destroyed like you are in creative mode and drops the block on the ground. When you try the same with shovel from tinkers it just destroy the block and nothing drops.

**Comment by BBoldt** [comment]
That's just how chisel is right now. One of the reasons I have it marked "unstable".

https://github.com/Chisel-Team/Chisel/issues/108
