### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/ThePioneers#2]
- [x] Add invtweaks
- [x] recipe for bit bag
- [x] configure v tweaks better
- [x] update resourceful crops
- [x] jei not in cheat mode

**Comment by TehNut** [comment]
Disable VTweaks right click harvesting of crops and use [SimpleHarvest](http://minecraft.curseforge.com/projects/simpleharvest). The VTweaks version doesn't work.

**Comment by BBoldt** [comment]
bit bag recipe is wool around a bit, idk why it doesn't show in JEI
