### ISSUE TITLE
NeoTech & Substratum Tin not interchangeable

### ISSUE THREAD

**Issue by Apocryphai** [BBoldt/ThePioneers#20]
Grinding Tin Ore (both NeoTech and Substratum) in the NeoTech grinder produces Substratum Tin Dust which smelts to Substratum Tin Bars which can't be used in the NeoTech recipes, e.g. the Basic RF Storage.

Edit: forgot to say that I haven't checked if there's similar issues with other metals but there are two different Tin Ores (NeoTech, Substratum), Lead Ores (Hydraulicraft, Substratum) and three Copper Ore types (Hydraulicraft, NeoTech, Substratum). Is there a way to unify these at all, or make sure they're interchangeable in recipes?

**Comment by TheRangerX** [comment]
Second this. This goes for any method for trying to double the NeoTech Tin ore. All methods create the Substratum version. Which wouldn't be that bad if NeoTech recipes allowed for OreDictionary ingots.
