### ISSUE TITLE
Can't craft Fluxed Solars Gold Solar Panel

### ISSUE THREAD

**Issue by Apocryphai** [BBoldt/ThePioneers#25]
Recipe shows up OK in JEI, won't craft in any crafting table.

**Comment by BBoldt** [comment]
https://dl.dropboxusercontent.com/u/134976541/ShareX/2016-02/2016-02-23_22-04-41.mp4

**Comment by Apocryphai** [comment]
How odd! I'll reinstall the pack next version :)
