### ISSUE TITLE
Possible Neotech Dupe with Dimensional Crates

### ISSUE THREAD

**Issue by Jebus83** [BBoldt/ThePioneers#28]
Hey BBoldt,

Playing on your The Pioneers 1.8.9 pack on the Requiem server (amazing pack btw).  For some reason I am able to place and break the Neotech Dimension Crates and gain them back as dupes (place 4, break, and get 8 back...so on and so forth). 

Definitely not lag or a quick issue as I have recreated it over 5 hours, logging on and off, and still able to do it. Went from 4 placed to like two stacks of 64 over that time.  Gonna put in neotech as well just in case :)

Jebus

**Comment by derimagia** [comment]
I was able to reproduce this as well.

**Comment by BBoldt** [comment]
https://github.com/TeamBR-Modding/NeoTech/issues/162
