### ISSUE TITLE
Leaking Memory after update to Release 4

### ISSUE THREAD

**Issue by MagnusRevang** [BBoldt/ThePioneers#29]
After updating from release 3 to release 4 I'm experiencing crazy lag spikes from Garbage collection after about 1 hour of flawless play - restarting the world cures it until another hour has passed. Installed OptiFine to counter it - didn't work, but the lagometer pointed to Garbage Collection being the problem. Running on x64, 4gb of RAM allocated on -xmx

**Comment by cauliflower69** [comment]
We are experiencing the same with the latest update on our server.

**Comment by BBoldt** [comment]
http://pastebin.com/yZP1RFy6

**Comment by AuricPolaris** [comment]
Oh look, that is my pastebin because I cannot google things. Sorry about that!

**Comment by cauliflower69** [comment]
Ok after some testing it seems that the culprit is Malisis' doors. Once the four mods were disabled the memory leak is fixed

**Comment by MagnusRevang** [comment]
@cauliflower69 I found the same thing in my testing - turning off those 4 mods cured the problem for me too

**Comment by Ordinastie** [comment]
If you could determine what mod is causing a memory link, that would greatly help.

**Comment by cauliflower69** [comment]
@Ordinastie Its Malisis mods

**Comment by Ordinastie** [comment]
I got that. I'm asking which one. :)

**Comment by cauliflower69** [comment]
I just disabled them all.

**Comment by Ordinastie** [comment]
And that doesn't really help me on fixing it...

**Comment by cauliflower69** [comment]
Well it stops the memory leak so it is "fixed" also it wouldn't take you long to load each mod individually to find the issue. 

Please report back with your findings

**Comment by BBoldt** [comment]
@Ordinastie Sorry I can't be more help, but i'm just going to remove your mods from my pack for now.

I don't have as much time and motivation to debug things as I had before, that and I'm losing interest in minecraft. Nothing personal.
