### ISSUE TITLE
Server lagging Client

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [BBoldt/ThePioneers#32]
Yeah, it doesn't make sense to me either, and no one has been able to figure it out.
http://paste.feed-the-beast.com/view/32bf337b

All (2) players have randomly started receiving lag after an interval of the server being up, which causes anything from unresponsive clients to mobs that are so lagged they can't even detect you properly. For the first hour of the server after creation, there were no issues.

Considering both of us have a decent computer, (Alright mine's pretty crap, i'll admit), and neither of us lag in SSP, i'd say it's most likely the server.

**Comment by BBoldt** [comment]
I think it might be related to this:

https://github.com/BBoldt/ThePioneers/issues/29

**Comment by UnstableCodeScarlet** [comment]
Yeah i was debating on that, but i didn't notice a memory leak, i'll have to check later.

**Comment by cauliflower69** [comment]
@UnstableCodeScarlet can you disable Malisis' mods and see if that fixes the issue?
