### ISSUE TITLE
Malisis' Door Crash

### ISSUE THREAD

**Issue by AuricPolaris** [BBoldt/ThePioneers#34]
Crashlog: http://pastebin.com/xCyLtzkA

Forge Version: forge-1.8.9-11.15.1.1755-universal

Sponge Version: spongeforge-1.8.9-1732-3.1.0-BETA-1164

Was in a boat, and then I crashed from Malisis' doors. I do not fully understand what happened as none were present in the world.

**Comment by MagnusRevang** [comment]
See issue #29 - Malisis door is probably to culprit for some memory leaking, turning off those 4 mods cured my lag spikes and the same thing on another server
