### ISSUE TITLE
Ezstorage

### ISSUE THREAD

**Issue by ubedeadnow** [BBoldt/ThePioneers#36]
When trying to pull items from the system and then closing the gui, the items change in my inventory. I also cannot seem to break the controller either.

**Comment by MagnusRevang** [comment]
That happend to me when I turned off a mod and had an item from that mod in my system. Roll back to backup and remove the items that belong to mods that is taken out w R5, or add the removed mod back in, and it will appear in the storage, and remove it before turning it off again

**Comment by ubedeadnow** [comment]
I play on a server in which I am not an OP or can control the rolling back of the server.

**Comment by johnfg12** [comment]
having same issue i can get u logs if it will help?
