### ISSUE TITLE
Eye of ender

### ISSUE THREAD

**Issue by Atoru** [BBoldt/ThePioneers#40]
If I click with the eyes of ender nothing happens, they just stay in my hand instead of showing me the way to the stronghold... (release 4 and release 5)

**Comment by Atoru** [comment]
eye of ender works in single player just not on server, but I did find the portal on the server by setting my SP worlds seed to be the same as the one on the server...

**Comment by unascribed** [comment]
Eyes of Ender work fine for me in survival multiplayer.

**Comment by BBoldt** [comment]
Yeah I haven't had any issues either, in any versions of the pack.

Atoru are you sure it's not server lag or something?

Please try again with the next version of the pack.
