### ISSUE TITLE
Blood Magic - Well of Suffering

### ISSUE THREAD

**Issue by Atoru** [BBoldt/ThePioneers#41]
When me and my buddy tried to setup the well of suffering and activate it we got the message "you feel that these runes are not configured correctly"
We tried to move the ritual to a different altar and also place it just in mid air and activate it - as result we always get the same message for missconfigured runes....

screenshot of message after activating the ritual: http://puu.sh/nDVRc/8721b27aee.png

modpack version: Release 5

**Comment by peeken1** [comment]
Same with the ritual of the feathered knife

**Comment by TehNut** [comment]
Are you sure that the Activation Crystal is bound to you? A minor bug has it print `chat.BloodMagic.ritual.notValid` instead of `chat.BloodMagic.ritual.weak` when the crystal is unbound.

**Comment by Atoru** [comment]
yeah tried making another activation crystal and it bounded to me when I right clicked it... the one we used yesterday was unbound and could not get it to bind...

**Comment by TehNut** [comment]
Did it still not work?

**Comment by Atoru** [comment]
it worked with the new crystal.... but I have no idea why we could not activate the other one

**Comment by BBoldt** [comment]
If this is still a problem, it's not getting fixed as BM has moved on to 1.9 development.
