### ISSUE TITLE
Bucket/Clay Dupe with Stained Clay to Hardened Clay

### ISSUE THREAD

**Issue by kiwifails** [BBoldt/ThePioneers#42]
The MineTweaker script to turn any of the stained clay to hardened clay is causing the bucket that's returned to well, do strange things. It returns a bucket that, when right clicked on an infinite water source, spawns an infinite amount of buckets of water. It also dupes the clay blocks.

Here's a GIF showing the behavior: https://i.gyazo.com/eb19698f37f7f9783d86379c7af2686c.gif

I fixed the bucket dupe by replacing `<minecraft:water_bucket>.transformReplace(<minecraft:bucket>)` with `<minecraft:water_bucket>.giveBack(<minecraft:bucket>)`

I've not figured out how to fix the clay dupe :/

**Comment by BBoldt** [comment]
Well this looks like a fun one, it's probably a bug in minetweaker. I'll report it to Jared.

**Comment by BBoldt** [comment]
Fixed it. TOOK NO TIME AT ALL!

```
// # MINECRAFT #
recipes.addShapeless(<minecraft:grass> * 4, [<minecraft:water_bucket>, <minecraft:dirt>, <minecraft:dirt>, <minecraft:dirt>, <minecraft:dirt>, <minecraft:tallgrass:1>, <minecraft:tallgrass:1>, <minecraft:tallgrass:1>, <minecraft:tallgrass:1>]);
recipes.addShapeless(<minecraft:clay_ball> * 16, [<minecraft:water_bucket>, <minecraft:dirt>, <minecraft:dirt>, <minecraft:sand:*>, <minecraft:sand:*>, <minecraft:gravel>, <minecraft:gravel>, <minecraft:gravel>, <minecraft:gravel>]);
recipes.addShapeless(<minecraft:clay_ball> * 4, [<minecraft:clay>]);
recipes.addShapeless(<minecraft:hardened_clay> * 8, [<minecraft:water_bucket>, <minecraft:stained_hardened_clay:*>, <minecraft:stained_hardened_clay:*>, <minecraft:stained_hardened_clay:*>, <minecraft:stained_hardened_clay:*>, <minecraft:stained_hardened_clay:*>, <minecraft:stained_hardened_clay:*>, <minecraft:stained_hardened_clay:*>, <minecraft:stained_hardened_clay:*>]);
```

It turns out you just put <minecraft:water_bucket> in a recipe and minecraft gives you one back automatically.
