### ISSUE TITLE
Botania Alfglass Flask dupe

### ISSUE THREAD

**Issue by Atoru** [BBoldt/ThePioneers#44]
When you drink up a potion out of a Flask that has only 1 usage left the potion does not get emptied instead you get the effect from it and an unlimited (as many empty slots as you have in your inventory) amount of empty flasks in your inventory

Only way to stop the empty flasks to get spawned in your inventory is to drop the 1 usages left potion flask...

... Release 5

**Comment by williewillus** [comment]
If you are using Sponge, try without it

**Comment by Atoru** [comment]
hmm can't reproduce it in SP...

**Comment by williewillus** [comment]
See williewillus/Botania#168

**Comment by williewillus** [comment]
Both Botania and Sponge have patched this out, should be fixed in the next update of either
