### ISSUE TITLE
Zombie Pigmen not spawning in the Nether

### ISSUE THREAD

**Issue by MagnusRevang** [BBoldt/ThePioneers#45]
I have not seen a single Zombie Pigman in the Nether - plenty of firebats, ghasts and wisps, but the Pigmen is suspiciously absent (which means the nether spawns a lot more bats, ghasts and wisps to fill the mob quota)

**Comment by Atoru** [comment]
for us it's the same - no pigmen and no wither skeletons spawn in the nether
also if I place a skeleton spawner in the nether it does not spawn any wither skeletons - just regular skeletons,...

**Comment by MagnusRevang** [comment]
I have plenty of Wither skeletons (they only spawn inside Nether Fortresses), but it seems regular skeletons spawn more often than the vanilla 5% (I think it is). Have not tried to skeleton spawner thing, but I'm probably trying it soon - need more Wither skulls :-)

**Comment by Ozimundis** [comment]
I've been having ZPM's come through my portal, overworld side. Going through the portal, there are only the ones i've knocked back into the portal visible in the nether

**Comment by MagnusRevang** [comment]
It's V-Tweaks that's the culprit - it has a config flag to disable pig zombies. Since Intangible is in the same modpack and that relies on Pigmen, this seems strange. In fact, the mod seems to only make the game easier, why is it there?

**Comment by BBoldt** [comment]
I suspected v-tweaks, but I didn't see the config option when I checked.

That mod has some annoying defaults.

**Comment by MagnusRevang** [comment]
He calls it Pig Zombies, so a search for Pigman would fail. I would vote to get rid of it, plenty of other mods that will give harvest and planting on right click. Then I would also include Extra Util, Ender IO, Computercraft and Automagy. Will there be an update soon, btw?

**Comment by BBoldt** [comment]
Been kinda busy, just reinstalled my OS.

The new curse client was giving me shit as well. An update will come eventually.

**Comment by MagnusRevang** [comment]
The new Curse client is horrible, I'm an UX expert by day and I don't know what they've thought. Symptoms of a web designer doing application design on a very poor specification. Looking forward to an update, hopefully soon.
