### ISSUE TITLE
Quantum Flux block break

### ISSUE THREAD

**Issue by Chaogomu** [BBoldt/ThePioneers#47]
Left clicking on a RF Entangler breaks the block instantly with no drop.

Verified in single player as well.

**Comment by joekaiser** [comment]
FYI, I fixed this bug. (https://github.com/joekaiser/QuantumFlux/issues/86) It is included in the 2.0.1 release

**Comment by BBoldt** [comment]
Thanks @joekaiser, I will do a pioneers update this weekend. Kinda waiting on the buildcraft update that fixes compatibility with extra utils.

**Comment by joekaiser** [comment]
No rush on my end :)
