### ISSUE TITLE
Soul Shards - boosting shards with shards

### ISSUE THREAD

**Issue by Atoru** [BBoldt/ThePioneers#50]
If I make a tier 1 (or any other tier) soul shard of any mob and place it in a soul cage to get the mob to spawn, I can then boost another shard by killing the mobs that where spawned from the soul cage/shard...

I know that this was not possible in older versions of soul shards - the old ways

**Comment by TehNut** [comment]
https://github.com/TehNut/Soul-Shards-The-Old-Ways/blob/1.8/src/main/java/com/whammich/sstow/ConfigHandler.java#L70

**Comment by MagnusRevang** [comment]
This quickly becomes OP. In my private variant of Pioneers I turned that off. Due to Roguelike Dungeons giving you a gazillion spawners, I turned down the number a spawner gives you to 128 as well (you then need 8 spawners for tier 5). Seems more balanced.
