### ISSUE TITLE
Forge Version

### ISSUE THREAD

**Issue by leeber** [BBoldt/ThePioneers#52]
could you please include in the discription somewhere whichever forge version each release is using? The most reliable way to get it is to check the client after running, but if you're trying to GET the client running, you can't do that...

**Comment by Nuclearsmilz** [comment]
You can actually find this in the curse launcher, right about.... [here](https://gyazo.com/69b4774ad3a8cac651385a567831a25e)

**Comment by leeber** [comment]
There is a portion of the playerbase that can not use the curse launcher. It's possible to extract the pack itself without needing the curse launcher. However, you need the correct version of forge to run it, which is not included.

**Comment by BBoldt** [comment]
I'll post it somewhere more prominent in the future. In the meantime, take a look at the manifest.json that is included in the zip you download. It lists the forge version at the top.
