### ISSUE TITLE
RTG not using BiomesOPlenty

### ISSUE THREAD

**Issue by MagnusRevang** [BBoldt/ThePioneers#57]
You need BiomeTweaker and a custom script in order for RTG to use Biomes O Plenty. I have a script, would create a request if the git code was updated, but it's not :-) (the script available from RTG uses wrong ids, put biomes in the wrong climate zone and does not weight the additional biomes)

**Comment by BBoldt** [comment]
Sorry, haven't gotten git setup on my computer since I reinstalled my OS a while ago.

@unascribed has a working script too, I don't know if he did all the things you did though

**Comment by unascribed** [comment]
I didn't do weighting as I wasn't aware of it, but I do have a script with the correct biome IDs.

**Comment by BBoldt** [comment]
I'm not sure I want to include BiomeTweaker with the pack, as I believe it overrides the "regular" biomesoplenty world type entirely. Also the vanilla world type.

If it only worked in the Realistic World Gen world type, I would add it. Thoughts?

**Comment by BBoldt** [comment]
@unascribed or @MagnusRevang 

PR your config files into the repo, and next release I will add a note to the mod page that if you want it to work you will need to install biometweaker yourself.
