### ISSUE TITLE
Thaumcraft freezes the game when clicking Aspects of Magic in the Thaumonomicon

### ISSUE THREAD

**Issue by mickdekkers** [BBoldt/ThePioneers#60]
I'm not sure if this is the right place to report this, but I [can't report it](https://github.com/Azanor/thaumcraft-5/blob/master/contributing.md) at the Thaumcraft 5 repo since the modpack isn't using the latest version of forge.
There is no crash log because the game just freezes and becomes unresponsive, then Windows offers to stop the process when you click anywhere.

Can anyone confirm whether they're having this issue too?

**Comment by BBoldt** [comment]
Yes, I have this issue as well. Haven't had a chance to look into it yet, it's been a problem for a while.

If you wait like a minute after clicking aspects of magic, it should open.

**Comment by williewillus** [comment]
Sounds a lot like some mod is accessing the internet on the main thread (which is very dumb) and then repeatedly 404's until it times out
If you could somehow attach a debugger to the game you could probably see whose code is running right before it happens

**Comment by unascribed** [comment]
The Aspects of Magic page does this as well in 1.7 if you have scanned a *lot* of items, so my guess is since they removed scanning in TC5, it's freezing while it iterates over every single item in the pack.

**Comment by williewillus** [comment]
why is it iterating through everything instead of caching >.>
