### ISSUE TITLE
Neotech's Basic RF Batteries are crafted with 0 durability, breaking JEI's "Move items into crafting area"

### ISSUE THREAD

**Issue by SoullessWaffle** [BBoldt/ThePioneers#62]
Works with regular crafting, notice the 0 durability: ![](http://puu.sh/ovBk1/f7d04a2182.png)
Also notice the extra Basic RF Batteries in my inventory.

I'm unable to click the `+` icon because JEI says the Basic RF Batteries are missing: ![](http://puu.sh/ovBGu/2e916f254c.png)

JEI seems to think the recipe requires _undamaged_ Basic RF Batteries: ![](http://puu.sh/ovBwO/29a726bc8b.png)

Update: After crafting the Basic RF Storage item shown in the pictures, I noticed it also crafted that with 0 durability.

Update: I just crafted a Basic RF Battery using a Buildcraft Auto Workbench and it seems to be undamaged.

**Comment by BBoldt** [comment]
@mezz or @Dynious is there anything that can be done about this in the future?

Closing it here though since it's likely it wont be fixed in 1.8.9.

**Comment by mezz** [comment]
I can't tell if this is a JEI issue or not without looking a lot deeper into it.
Can you make a new issue on the JEI github?
