### ISSUE TITLE
Random server crash

### ISSUE THREAD

**Issue by cauliflower69** [BBoldt/ThePioneers#63]
http://pastebin.com/0rf9Htfw

**Comment by BBoldt** [comment]
There is a newer version of plant mega pack that I will update to, we are on 19 and 21 is the newest. I don't know how this error can be reproduced but hopefully this fixes it.

**Comment by BBoldt** [comment]
I went ahead and reported this to the Plant Mega Pack author so if there is any other information you may be able to add about this crash, let me know.

http://10paksmods.net/forum/showthread.php?tid=4&pid=1105#pid1105

**Comment by cauliflower69** [comment]
Sorry at the moment no more information from me. Maybe update and see how it goes?
