### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MrTubzy456** [BBoldt/ThePioneers#64]
Getting lots of crashes on Requiem. Here's the pastebin: http://pastebin.com/Kh6ieESw

After people crash the server isn't recognizing that they're crashed so, it sends the server into a loop where it looks for a player that\s not there. It says they're still there but, they're not.

**Comment by BBoldt** [comment]
I'm not sure but this may be relating to IC2?

I know Requiem has removed that mod, have these crashes persisted beyond that removal?

**Comment by MrTubzy456** [comment]
Hey it's Tubz from requiem. Yeah, Cauli finally got tired of it crashing the server all the time and pulled it. We still get that crash if people join and haven't disabled IC2 in their client. This is such a weird issue. I just wanted to let you know about it. I have no idea what to do about it and neither does Cauli. Hopefully everyone will get that disabled in their pack and that'll fix the issue till ic2 issues a fix.

**Comment by BBoldt** [comment]
http://bt.industrial-craft.net/view.php?id=1869
