### ISSUE TITLE
Aura Cascade Encyclopedia Aura crash

### ISSUE THREAD

**Issue by WarMind666** [BBoldt/ThePioneers#65]
Upon viewing any page within the Encyclopedia Aura that showcases a multiblock build within the book, after a few seconds the game will crash.  I downloaded through the Curse launcher, and have not adjusted any mods or configs within the pack.  This error has happened multiple times, and it only happens on the multiblock pages within the book, everything else in the book operates fine.

http://pastebin.com/XQzpCTDy

**Comment by BBoldt** [comment]
This is not going to be fixed, sorry. Aura Cascade is dead in 1.8.9.
