### ISSUE TITLE
What is wrong with my launcher? 

### ISSUE THREAD

**Issue by PlasmaNoodle** [BBoldt/ThePioneers#66]
I hit the play button at the bottom of the MC launcher and it launches fine, but it then disappears and reappears with a new tab called game output and this error or something in this paste right [here](http://pastebin.com/TRnWsJd5)

**Comment by williewillus** [comment]
are you using the vanilla launcher? 0.o

**Comment by BBoldt** [comment]
I think the download may be corrupted, try reinstalling the launcher or the modpack, maybe both.

Also make sure you have dedicated enough memory in the settings.

**Comment by PlasmaNoodle** [comment]
I am using the curse launcher and i have redownloaded twice both the pack and the launcher.

**Comment by BBoldt** [comment]
You need to try getting support from curse, it's not something on my end. Press the little "help" question mark in the curse launcher and send the bug report to them.


![](http://i.imgur.com/MKfythq.png)
