### ISSUE TITLE
Consider adding EnderIO to the pack

### ISSUE THREAD

**Issue by SoullessWaffle** [BBoldt/ThePioneers#68]
I added the 1.8.9 version of [EnderIO](http://enderio.com/) to my Pioneers instance a couple of days ago and it's been a ton of fun.

Aside from some minor visual glitches in the conduit GUI, everything seems to work.
Alloy Smelter works, SAG Mill works, basically all the machines I've used so far work without any problems.
The Dark Steel Sword ("The Ender") with the Travel upgrade is AMAZING by the way.

You can get the mod files here (you'll need both):
[EnderCore 1.8 Beta](http://ci.tterrag.com/job/EnderCore-1.8/)
[EnderIO 1.8 Alpha](http://ci.tterrag.com/job/EnderIO-1.8/)

**Comment by BBoldt** [comment]
I can't distribute that on curseforge. EnderIO team need to upload it there for me to add it.

**Comment by SoullessWaffle** [comment]
Oh, that's a shame. Couldn't you add it as an "override", like Charset, Flamingo, and Plant Mega Pack?

**Comment by BBoldt** [comment]
Nope, that only works for mods not on curseforge.
