### ISSUE TITLE
Is there any alternative to 1.7.10 ExtraUtilities' Filing Cabinets?

### ISSUE THREAD

**Issue by SoullessWaffle** [BBoldt/ThePioneers#69]
Unfortunately ExtraUtils2 hasn't added them yet.

[FTB Wiki: Filing Cabinet](http://ftbwiki.org/Filing_Cabinet)
[FTB Wiki: Filing Cabinet (Advanced)](http://ftbwiki.org/Filing_Cabinet_(Advanced))

Does anyone know of any other 1.8.9 mod that adds a way to store lots of unstackable items?
In my case I have an Enderman farm that's rapidly filling up chests with damaged/enchanted armor pieces.

@BBoldt I wasn't sure where to ask this so feel free to close this issue if this is not the right place for it.

**Comment by BBoldt** [comment]
Best place to ask is the subreddit, the discord, or twitter.

I would suggest trying out Ender Rift for all your *anything storage* needs. Or just void the damaged stuff. :stuck_out_tongue:
