### ISSUE TITLE
Random Teleporting

### ISSUE THREAD

**Issue by ajmaines** [BBoldt/ThePioneers#74]
During normal game play, inventory management, combat, etc my character will teleport to a random location nearby. The teleportation is not lag because I have been teleported to areas not yet discovered. Current area is a Roguelike Dungeon where I was teleported to a random cave nearby.  No particular action triggers the movement. Any ideas?

**Comment by BBoldt** [comment]
Yes, there is a random things "Ender Core" in your vicinity.

Not entirely sure what they are used for other than to confuse you.

https://www.reddit.com/r/feedthebeast/comments/41xs8a/18_random_things_help/

**Comment by ajmaines** [comment]
Thank you for the quick response.

**Comment by BBoldt** [comment]
The ender core should be on the surface somewhere. It's like a 3x3 chunk of obsidian wrapped around another block.

I don't know if it can be broken in survival, but you can probably kill it in creative.
