### ISSUE TITLE
Items in inventory randomly disappearing

### ISSUE THREAD

**Issue by WarMind666** [BBoldt/ThePioneers#75]
#### Questions:
- Are you on the latest version of the modpack?:
- Have you added any additional mods, and if so, have you tried reproducing the issue without them?:
- Server or client issue?:

**Comment by BBoldt** [comment]
Some sort of desync I guess, but I have not experienced it myself.

**Comment by washinoboku** [comment]
I have the same issue. I can reproduce it with a quartz square planter form plant mega pack. Try it to put some flowers in it and they disappear, even in inventory, until open some kind chest item. Sometimes crashes the game.

Sorry if my english is bad.
