### ISSUE TITLE
fluid incompadability

### ISSUE THREAD

**Issue by Spikeball** [BBoldt/ThePioneers#76]
#### Questions:
- Are you on the latest version of the modpack?: Yes
- Have you added any additional mods, and if so, have you tried reproducing the issue without them?: No extra mods
- Server or client issue?: single player (Both?)

**Comment by BBoldt** [comment]
I agree, but I can't really do anything to fix this. Tinkers' and Foundry have moved way past 1.8.9. There is nothing I can do with Minetweaker really.

Any suggestions on how to fix this problem?

My suggestion is to just use the Induction Crucible Furnace for making liquid brass and pretend it's not the same thing. :P

**Comment by Spikeball** [comment]
Oh well.
I wasn't sure who had to do the ore dictionary(I think this is where the interchangeability of fluids is handled) registration.
due to how hard it was to get Tinkers' to melt the stuff I think they are the one with the unregistered liquid.
Thank you for the response.

**Comment by BBoldt** [comment]
@Spikeball You should put together a little test pack in 1.10 with JEI + Tinkers + Foundry and see if the issue is still there. If it is, you can report it to the right people and it will at least be fixed in future versions!
