### ISSUE TITLE
Minecraft The Pioneers mod crashes upon loading world.

### ISSUE THREAD

**Issue by jesperf1** [BBoldt/ThePioneers#77]
#### Questions:
- Are you on the latest version of the modpack?: Yes i am. 1.8.9
- Have you added any additional mods, and if so, have you tried reproducing the issue without them?: No i haven't.
- Server or client issue?: Client issue.

**Comment by BBoldt** [comment]
Looks to be an issue involving IC2, try disabling that mod and loading the world without it.

If it still doesn't work, give me the new crashlog that gets generated.
