### ISSUE TITLE
Random Client Crashes on server Reconnect.

### ISSUE THREAD

**Issue by Devious-Neo** [BBoldt/ThePioneers#79]
Afternoon.
 I am having an issue that i'm hoping you are able to help me troubleshoot.
I have a server setup running the latest Pioneer modpack (v8). The server itself runs fine, and I am yet to experience anything too out of the ordinary, however there is an issue I have noticed and it is somewhat frustrating. If you are disconnected from the server, or even sometimes if you disconnect yourself when you attempt to reconnect to the server you are crashed back to the launcher. As I have access to the server I have provided all logs that I can. 
Note: The server is running SpongeForge mod, along with a few other mods/plugins (visable in logs) however the issue is Client side, not server side so I do not believe that Sponge is the culprit, and I have also tested with all additional mods/plugins (SpongeForge included) disabled server side and the issue still occurs. 

The issue is repeatable if I kick myself via console (as seen in the logs), when I try to reconnect I get crashed to launcher every time. If you disconnect manually, its seems random whether or not the issue occurs then. Once the pack is rebooted you are able to reconnect without issue until you disconnect again. 

I have tried with multiple versions of Java both client side and server side, and also with fresh maps, and im truly at a loss to figure out the exact cause. It is happening to everyone who has connected to the test server.

Any insight that you can offer would be greatly appreciated. 

Client Crash Log - http://pastebin.com/X3cTyLPk

server latest.log - http://pastebin.com/XMwr6bPS

fml-server-latest.log - http://pastebin.com/Jze0jxgF

Thanks for your time. Truly loving the balance of the pack, fantastic work by the way :)
- Devious

**Comment by BBoldt** [comment]
#64

http://bt.industrial-craft.net/view.php?id=1869

Only solution is to remove IC2. :(

**Comment by BBoldt** [comment]
According to the IC2 devs, it's a mod conflict. One of the other mods in the pack is messing up IC2. If you can find out which one you win a prize!

**Comment by Devious-Neo** [comment]
Haha fair enough then. My apologies about posting an issue that had already been reported, I will do some further testing and report back if I manage to find the culprit. 
Thanks again. 
-Devious

**Comment by slidingmike** [comment]
Don't want to bump an old issue but interested in @Devious-Neo had any luck with identifying a possible issue.
