### ISSUE TITLE
I can't get to the Minecraft title screen in Pioneers

### ISSUE THREAD

**Issue by blazeblades** [BBoldt/ThePioneers#80]
Hello! First of all thank you for playing the pack, hope you are enjoying it! Sorry you're experiencing an issue. Follow the instructions here and I'll do my best to help. Note I am not some sort of wizard and there may be issues which I will be unable to solve from time to time.

Before you write anything:
* Check to see if your issue has been posted before.
* Make sure you're on the latest version of the modpack.

Thanks again for taking the time to submit a bug report!
-->

**Issue Description:** I will get to this place in the loading:
Loading - Completing Minecraft Initialization
7/7
Loading Resources - Reloading Listeners
143/143
Reloading - ModelManager
29/44

Then it just stops loading, and I had my entire computer freeze one time I tried opening it.

**Steps to Reproduce:**I open the Curse launcher, click play on Pioneers, then play on the Minecraft launcher that opens, and wait.

**Crash report or log (uploaded to gist.github.com or pastebin.com):**http://pastebin.com/T18DXeaY

**Comment by BBoldt** [comment]
java.lang.OutOfMemoryError

Go into the curse launcher settings and dedicate more memory to minecraft.
