### ISSUE TITLE
Ritual Diviner Desync

### ISSUE THREAD

**Issue by palaster** [BBoldt/ThePioneers#83]
**Issue Description:**
When using the ritual diviner, from Blood Magic, the runes places aren't updated on all clients, except for the player placing the runes. But, I have only tested this with the Sounds of Cleansing Soul and Ritual of Living Evolution, I might have gotten the names wrong for the rituals.

**Steps to Reproduce:**
1) Use the ritual diviner on a master ritual stone, to build a ritual.
2) All nearby players won't see the runes placed, until the leave and rejoin the server.

**Crash report or log (uploaded to gist.github.com or pastebin.com):**
No crash report.

Edit - The Ritual Diviner was also a Dusk Level.

**Comment by BBoldt** [comment]
Nothing I can do, Blood Magic 1.8.9 is dead.
