### ISSUE TITLE
Demonic will not dropping again?

### ISSUE THREAD

**Issue by Beefjerkyy** [BBoldt/ThePioneers#85]
**Issue Description:**I have spent many many hours with blood magic snares trying to get a single demonic will to start the mod. There is little information on drop rates that I can find and do not know if I am unlucky or if this issue has come back. I have gone through (A guess) 300+ snares and a couple hundred kills with the white particle effects. The server is on revision 7.

**Steps to Reproduce:**Unknown

**Comment by Beefjerkyy** [comment]
Definitely an issue somewhere. Had someone spawn some demonic wills for me. I would see them drop on the ground and then as soon as I hear the sound for them being picked up they would disappear.

**Comment by Beefjerkyy** [comment]
Still not working as of revision 8 at the moment.

**Comment by Beefjerkyy** [comment]
Turns out it was a server issue. A conflict with sponge that has been fixed.

**Comment by BBoldt** [comment]
Yeah sorry for not responding to this, been busy lately.

I tested it and couldn't reproduce it so I forgot to reply.
