### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Dinip** [BBoldt/ThePioneers#86]
Server crash during startup
http://pastebin.com/fJJQvWDA

**Comment by zaknirahc** [comment]
I've got the same issue. I'm not very good at reading crash logs but it looks like the website Adobe Blocks uses to check versions is down and causing it to crash.

**Comment by BBoldt** [comment]
Is this still happening?

**Comment by zaknirahc** [comment]
The problem still exist but there is an update that fixes it. http://minecraft.curseforge.com/projects/adobe-blocks-2/files/2312557

**Comment by BBoldt** [comment]
Yeah, I'll take care of it soon
