### ISSUE TITLE
High tickrate due to Thaumcraft

### ISSUE THREAD

**Issue by ghost** [BBoldt/ThePioneers#87]
For a while now I've had some issues with the performance (as in high tickrate) with my server. It's me and 1 friend, but I'm pretty much alone there. We haven't build anything crazy or stupid that could create some obvious issues.
The log is full of these messages:

> [11:45:48] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2147ms behind, skipping 42 tick(s)
> [11:46:36] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2626ms behind, skipping 52 tick(s)
> [11:47:11] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2173ms behind, skipping 43 tick(s)

And in the console you can see Thaumcraft complaining as well:

> > > [11:44:13] [Thread-10/WARN] [THAUMCRAFT]: AURAS TAKING 1621 ms LONGER THAN NORMAL

I searched around to find a way to debug the issue and I found the application VisualVM. But I'm not sure what I'm looking at. [Here's the output of it anyway](http://i.imgur.com/Fseu3Ab.png). 

I'm currently hosting the server on my computer with an I7 4790K and 16G of Ram

**Comment by BBoldt** [comment]
How much memory do you have dedicated to the server?

**Comment by ghost** [comment]
i allowed 4G but i now have tried to downgrade forge and it seems to work fine

**Comment by BBoldt** [comment]
What did you downgrade forge to? I may need to do that as well.

**Comment by ghost** [comment]
I let the default version of forge on the client side, but on the server i downgraded to 1.8.9-11.15.1.1738 because i read somewhere that somebody fixed the problem this way. Maybe a newer version of forge works as well ...
