### ISSUE TITLE
Game Crash on FOV Change

### ISSUE THREAD

**Issue by rangicus** [BBoldt/ThePioneers#9]
Crashlog: http://pastebin.com/raw/Bj1ZmykN

Is as the title says, runs fine until FOV is changed. Immediately crashes.

**Comment by BBoldt** [comment]
Crashlog points to Zyin's HUD. Remove that mod for a temp fix, it's nothing critical.

**Comment by BBoldt** [comment]
https://github.com/Zyin055/zyinhud/issues/53
