### ISSUE TITLE
[Server][Crash][1.20.1-5.3.0] Modpack contains mods that should work on a server but load client only classes

### ISSUE THREAD

**Issue by TigerWalts** [BBoldt/ThePioneers#94]
**Modpack Version:** `1.20.1-5.3.0`

**Issue Description:**

Crashes on server start up. Multiple mods have bugs where client-only code is called:

- Simply Caterpillar - https://modrinth.com/mod/simply-caterpillar
- EC Create Plugin / EC Create Compatability - https://modrinth.com/mod/ec-create-compat

These mods should be server compatible but currently are not.

**Steps to Reproduce:**
Run as a server - This requires disabling all the client-only mods, you may also need to disable Embeddium:

```
appleskin-forge-mc1.20.1-2.5.1.jar
bcfp-1.20.1-1.0.0.jar
BetterAdvancements-1.20.1-0.3.2.161.jar
betterjukebox-1.20-1.2.jar
BetterThirdPerson-Forge-1.20-1.9.0.jar
bocchium-1.20.1-0.0.2.jar
Controlling-forge-1.20.1-12.0.2.jar
drippyloadingscreen_forge_2.2.4_MC_1.20.1.jar
entityculling-forge-1.6.2-mc1.20.1.jar
EquipmentCompare-1.20.1-forge-1.3.7.jar
fancymenu_forge_2.14.9-3_MC_1.20.1.jar
Forgematica-0.1.2-mc1.20.1.jar
ItemBorders-1.20.1-forge-1.2.0.jar
LegendaryTooltips-1.20.1-forge-1.4.5.jar
light-overlay-8.0.0-forge.jar
MaFgLib-0.1.3-mc1.20.1.jar
MouseTweaks-forge-mc1.20-2.25.jar
oculus-mc1.20.1-1.6.9.jar
textrues_embeddium_options-0.1.2+mc1.20.1.jar
TravelersTitles-1.20-Forge-4.0.1.jar
XaeroPlus-Forge-1.20.1-50-WM1.36.0-MM23.8.4.jar
```

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

- https://github.com/The-Fireplace-Minecraft-Mods/Simply-Caterpillar/issues/18
- https://legacy.curseforge.com/minecraft/mc-mods/ec-create-compat/issues/1

**Comment by BBoldt** [comment]
Thank you for the heads up on this, I'll keep it in mind for the next update and I'll include a working server pack. Still deciding on the final modlist for this version. Would like to lock it in before I release the serverpack.

**Comment by BBoldt** [comment]
The server pack takes quite a while to get approved on curseforge (several days). To anyone trying to make a server, instead of waiting just install the pack to your client and remove these mods: https://github.com/BBoldt/ThePioneers/blob/1.20.1/clientside_mods_removed_for_server.txt

I will try to keep the list up to date.
